server:
  port: 8761

spring:
  application:
    name: eureka-consumer-dev
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://spring-app:8960

debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-app:8660/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: http://spring-app:${server.port}/info
    healthCheckUrlPath: http://spring-app:${server.port}/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
