server:
  port: 8760
  
spring:
  application:
    name: eureka-consumer-dev
    
debug: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://spring-app:8660/eureka/
    healthcheck:
      enabled: true
  instance:
    statusPageUrlPath: http://spring-app:${server.port}/info
    healthCheckUrlPath: http://spring-app:${server.port}/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10

