spring:
  application:
    name: iot-data-mysql
server:
  port: 84

debug: false
logging:
  path: ./log

---
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://spring-app:3306/iotdb?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

jpa:
  database: MYSQL
  show-sql: true
  properties:
    hibernate:
      hbm2ddl:
        auto: none

redis:
  hostName: 127.0.0.1
  #端口号
  port: 6379
  #如果有密码
  password:
  #数据库(默认0)
  database: 0
  #客户端超时时间单位是毫秒 默认是2000
  timeout: 10000
  #最大空闲数
  maxIdle: 300
  #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
  #redis.maxActive=600
  #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis2.4以后用该属性
  maxTotal: 1000
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 1024
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true

---
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://spring-app:8960
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
  session:
    store-type: redis

eureka:
  instance:
    statusPageUrlPath: http://spring-app:${server.port}/info
    healthCheckUrlPath: http://spring-app:${server.port}/actuator/health
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://spring-app:8660/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign

management:
  endpoint:
    health:
      show-details: ALWAYS #health endpoint是否必须显示全部细节
  endpoints:
    web:
      exposure:
        include: "*" #暴露所有的端点我们可以看到更多的服务实例相关信息，
        exclude: env
    jmx:
      exposure:
        include: "*"
        exclude: env
